name: Build gato-x Windows Executable
on:
  workflow_dispatch: # This allows manual triggering
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install gato-x and dependencies
        run: |
          pip install pyinstaller colorama requests pyyaml cryptography networkx
          pip install .
      - name: Build executable
        run: |
          pyinstaller ./gatox/main.py --onefile --clean -n gato-x
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gato-x-windows
          path: dist/gato-x.exe
